version: '3.3'
name: "demo_tdd_post-it"
services:
  demo-db-mysql-prisma:
    container_name: demo-db-mysql-prisma
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'tdd_post-it'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'WCS'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'IntoTheWild'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'RootRoot'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
    volumes:
      - ./demo-db-mysql-prisma:/var/lib/mysql

volumes:
  demo-db-mysql-prisma: